### ISSUE TITLE
Documentation issue in R-devel

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkgbuild#105]
> For HTML help in R, markup of the form \link[pkg:foo]{topic} in R help
pages have traditionally been interpreted as links to the _file_
foo.Rd in package pkg, with fallback to the _topic_ (alias) foo in
case the file foo.Rd is not found. R-devel now interprets such markup
as links to the topic foo, with fallback to the file foo.Rd if the
topic foo does not exist, as this behaviour is more natural (and
implicitly assumed by many package authors).
>
> Your package is one of the few on CRAN containing links that change
its target help page depending on whether the new or old rules are in
effect. This happens because the target package contains both file
foo.Rd and topic foo, but in a different file.
>
> Ideally, we would like you to update your package so that the target
is unambiguously identified under both rules, so that these links work
as intended in both released and development versions of R. For
details on how this can be done, please see
>
> https://deepayan.github.io/tmp/topichelp/funs.html
>
> (and the corresponding Rd source at
https://github.com/deepayan/misc/blob/master/helptopic/man/funs.Rd).
>
> Kindly submit an update of your package to CRAN as soon as possible
fixing these issues. To test your changes, you need a recent version
of R-devel, where the new rule is the default, and the old rule can be
activated by setting
>
> Sys.setenv("_R_HELP_LINKS_TO_TOPICS_" = FALSE)

**Comment by gaborcsardi** [comment]
```
R CMD INSTALL --html .
```
is clean both with and without
```
export R_HELP_LINKS_TO_TOPICS=FALSE
```
so I am closing this.
