### ISSUE TITLE
Re-licensing pkgbuild

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgbuild#106]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/pkgbuild/graphs/contributors). @burgerga, @cderv, @dpastoor, @theGreatWhiteShark, would you permit us to re-license pkgbuild with the MIT license? If so, please comment "I agree" below.

* [x] [@burgerga](https://github.com/r-lib/pkgbuild/commits?author=burgerga)  
* [x] [@cderv](https://github.com/r-lib/pkgbuild/commits?author=cderv)  
* [x] [@dpastoor](https://github.com/r-lib/pkgbuild/commits?author=dpastoor)  
* [x] [@theGreatWhiteShark](https://github.com/r-lib/pkgbuild/commits?author=theGreatWhiteShark)

**Comment by dpastoor** [comment]
I agree

**Comment by burgerga** [comment]
I agree

**Comment by theGreatWhiteShark** [comment]
I agree

**Comment by cderv** [comment]
I agree

(Sorry for the delay ! 😅 )
