### ISSUE TITLE
Compiler flags for for C++14

### ISSUE THREAD

**Issue by const-ae** [r-lib/pkgbuild#112]
Hi,

I am maintaining a [package](https://github.com/const-ae/sparseMatrixStats) that depends on C++14 features. I tried to compile the package with debug flags, but noticed that `pkgbuild::with_debug(devtools::load_all())` had no effect on the optimization level. After some digging, I found that `withr::with_makevars(c(CXX14FLAGS = "-Wall -g -O0", devtools::load_all())` has the desired behavior.

As far as I can see, the problem comes from the fact that `pkgbuild` [defines](https://github.com/r-lib/pkgbuild/blob/master/R/compiler-flags.R#L30) the compiler flags only for C++11. 

Would it be possible to add a line for C++14 (and newer versions)?

Best Regards,
Constantin

**Comment by jimhester** [comment]
Sure, do you want to write a pull request to add the flags for C++14, C++17 and C++20?

**Comment by const-ae** [comment]
The pull request is at https://github.com/r-lib/pkgbuild/pull/113

**Comment by gaborcsardi** [comment]
This was fixed in #113.
