### ISSUE TITLE
Can we propagate build warnings to errors

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgbuild#114]
at least for `devtools::release()`?

Use case: a stray `testthat-problems.Rds` causes `R CMD build .` to increase (!!!) the version number in `DESCRIPTION` to 3.5 instead of failing the build. This is very easy to go unnoticed. Can we make this a failure here?

Related: https://github.com/r-lib/testthat/pull/1292.

It's an entirely different discussion if `R CMD build .` should ever touch my `DESCRIPTION`.

**Comment by gaborcsardi** [comment]
This seems hard, because `R CMD build` runs in a separate process, and the exit status is still zero if it bumps the version number.
