### ISSUE TITLE
Request: opt out of automated install prompt

### ISSUE THREAD

**Issue by karldw** [r-lib/pkgbuild#137]
Hello,

I saw the [documentation](https://r-lib.github.io/pkgbuild/reference/has_build_tools.html) for  `has_build_tools`, `check_build_tools`, and `with_build_tools` says "If run interactively from RStudio, and the build tools are not available these functions will trigger an automated install."
I'd like to use pkgbuild for some work that's not directly exposed to the user, so I would like to check `has_build_tools` without prompting an install process. Is that possible?

For testing on systems with build tools already installed, the following demonstrates the install prompt in RStudio:
```r
pkgbuild:::without_compiler(pkgbuild::has_build_tools())
```

Thanks!

**Comment by gaborcsardi** [comment]
Hmmm, you can already do this, actually, by setting an option:
```r
> options(buildtools.check = NULL)
> has_build_tools()
[1] TRUE
> pkgbuild:::without_compiler(pkgbuild::has_build_tools())
[1] FALSE
```

So I think we don't need to add anything for this, but you can delete that option temporarily, using `on.exit()` to restore it?
