### ISSUE TITLE
`pkgbuild::build(..., args=c())` failing

### ISSUE THREAD

**Issue by alexWhitworth** [r-lib/pkgbuild#159]
When building my package via `pkgbuild::build` instead of command line `R CMD BUILD` I am generating new errors.

## To Reproduce

- Clone: https://github.com/alexWhitworth/imputemulti
- run `R CMD BUILD imputeMulti --compact-vignettes='gs+qpdf'`
- run `R CMD CHECK ./imputeMulti_0.8.4.tar.gz`. result = "Status: OK"
- Now rerun in R:

```
$> R
R> devtools::check_built("./imputeMulti_0.8.4.tar.gz")  # result = "Status: OK"
R> pkgbuild::build("./imputeMulti", vignettes=TRUE, args= c("--compact-vignettes='gs+qpdf'"))
R> devtools::check_built("./imputeMulti_0.8.4.tar.gz") # result = "0 errors ✔ | 1 warning ✖ | 0 notes ✔"
```

> checking sizes of PDF files under ‘inst/doc’ ... WARNING
>    ‘gs+qpdf’ made some significant size reductions:
>     compacted ‘imputeMulti.pdf’ from 492Kb to 127Kb
>    consider running tools::compactPDF(gs_quality = "ebook") on these files

**Comment by gaborcsardi** [comment]
This does not have much to do with pkgbuild. `devtools::check_built()` uses different flags than plain `R CMD check`, in particular, it adds `--as-cran` by default.

**Comment by alexWhitworth** [comment]
@gaborcsardi running `R CMD CHECK ... --as-cran` does not reproduce the warning from `pkgbuild`
