### ISSUE TITLE
Adding R4.3 to version info

### ISSUE THREAD

**Issue by sjbonner** [r-lib/pkgbuild#164]
I recently upgraded to R 4.3.0 and tried to install RTools via the installr package. I found that it was trying to install RTools for R 4.2.0, and traced the problem to the definition of `version_info` in rtools-metadata.R. I think this needs to be updated to include R 4.3.

Thanks!

**Comment by gaborcsardi** [comment]
closed by b3c5f851300f83666ab79d03e539cfced46b4c9b
