### ISSUE TITLE
Cannot install the torchvision package, using https://blogs.rstudio.com/ai/posts/2020-09-29-introducing-torch-for-r/

### ISSUE THREAD

**Issue by lgawarec** [r-lib/pkgbuild#168]
I get the same error every time when I try to install torchvision. I tried Yes and No for the pop-up question on using sources. 
I first did the following:

install.packages("torch") 
install.packages("devtools") 
devtools::install_github("mlverse/torch") 
library(torch)

This command failed to execute
torch_tensor(1, device = "cuda")

Error in torch_tensor_cpp(data, dtype, device, requires_grad, pin_memory) : 
  PyTorch is not linked with support for cuda devices
Exception raised from getDeviceGuardImpl at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10/core/impl/DeviceGuardImplInterface.h:319 (most recent call first):
00007FFF3E8FAD1200007FFF3E8FACB0 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFF3E8FA79E00007FFF3E8FA750 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFEC811EC0500007FFEC811EA60 torch_cpu.dll!at::Context::getDeviceFromPtr [<unknown file> @ <unknown line number>]
00007FFEC85F0A4600007FFEC85F09B0 torch_cpu.dll!at::native::to [<unknown file> @ <unknown line number>]
00007FFEC92DA96800007FFEC92D4610 torch_cpu.dll!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFEC92C40ED00007FFEC928FAC0 torch_cpu.dll!at::compositeimplicitautograd::broadcast_to [<unknown file> @ <unknown line number>]
00007FFEC8AF510F00007FFEC8AF4EE0 torch_cpu.dll!at::_ops::to_dtype_layout

Here is my session for installing torchvision, please help, many thanks!

R version 4.1.3 (2022-03-10) -- "One Push-Up"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Warning: namespace ‘caret’ is not available and has been replaced
by .GlobalEnv when processing object ‘ctrl’
[Workspace loaded from ~/.RData]

Loading required package: ROCR

> devtools::install_github("mlverse/torchvision")
Downloading GitHub repo mlverse/torchvision@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: cli   (3.6.0   -> 3.6.1 ) [CRAN]
5: rlang (1.0.6   -> 1.1.1 ) [CRAN]
6: Rcpp  (1.0.8.3 -> 1.0.10) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
cli   (3.6.0   -> 3.6.1 ) [CRAN]
rlang (1.0.6   -> 1.1.1 ) [CRAN]
Rcpp  (1.0.8.3 -> 1.0.10) [CRAN]
Installing 3 packages: cli, rlang, Rcpp

  There is a binary version available but the source version is
  later:
      binary source needs_compilation
rlang  1.1.0  1.1.1              TRUE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/cli_3.6.1.zip'
Content type 'application/zip' length 1388241 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/rlang_1.1.0.zip'
Content type 'application/zip' length 1710397 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/Rcpp_1.0.10.zip'
Content type 'application/zip' length 3291415 bytes (3.1 MB)
downloaded 3.1 MB

package ‘cli’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘cli’
Warning: restored ‘cli’
package ‘rlang’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘rlang’
Warning: restored ‘rlang’
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
Warning: restored ‘Rcpp’

The downloaded binary packages are in
	C:\Users\lgawarec\AppData\Local\Temp\Rtmp8gy3Lz\downloaded_packages
-- R CMD build -------------------------------------------------------------
v  checking for file 'C:\Users\lgawarec\AppData\Local\Temp\Rtmp8gy3Lz\remotes2bc831b0207a\mlverse-torchvision-2d8b936/DESCRIPTION' ...
-  preparing 'torchvision':
v  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'torchvision/vignettes/examples'
   Removed empty directory 'torchvision/vignettes'
-  building 'torchvision_0.5.1.9000.tar.gz'
   
* installing *source* package 'torchvision' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'torchvision'
    finding HTML links ... done
    base_loader                             html  
    cifar10_dataset                         html  
    draw_bounding_boxes                     html  
    draw_keypoints                          html  
    draw_segmentation_masks                 html  
    image_folder_dataset                    html  
    kmnist_dataset                          html  
    magick_loader                           html  
    mnist_dataset                           html  
    model_alexnet                           html  
    model_inception_v3                      html  
    model_mobilenet_v2                      html  
    model_resnet                            html  
    model_vgg                               html  
    tensor_image_browse                     html  
    tensor_image_display                    html  
    tiny_imagenet_dataset                   html  
    transform_adjust_brightness             html  
    transform_adjust_contrast               html  
    transform_adjust_gamma                  html  
    transform_adjust_hue                    html  
    transform_adjust_saturation             html  
    transform_affine                        html  
    transform_center_crop                   html  
    transform_color_jitter                  html  
    transform_convert_image_dtype           html  
    transform_crop                          html  
    transform_five_crop                     html  
    transform_grayscale                     html  
    transform_hflip                         html  
    transform_linear_transformation         html  
    transform_normalize                     html  
    transform_pad                           html  
    transform_perspective                   html  
    transform_random_affine                 html  
    transform_random_apply                  html  
    transform_random_choice                 html  
    transform_random_crop                   html  
    transform_random_erasing                html  
    transform_random_grayscale              html  
    transform_random_horizontal_flip        html  
    transform_random_order                  html  
    transform_random_perspective            html  
    transform_random_resized_crop           html  
    transform_random_rotation               html  
    transform_random_vertical_flip          html  
    transform_resize                        html  
    transform_resized_crop                  html  
    transform_rgb_to_grayscale              html  
    transform_rotate                        html  
    transform_ten_crop                      html  
    transform_to_tensor                     html  
    transform_vflip                         html  
    vision_make_grid                        html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'torchvision' in library.dynam(lib, package, package.lib):
 DLL 'torchpkg' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-4.1.3/library/torchvision'
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.1.3\library\00LOCK\cli\libs\x64\cli.dll to C:\Program Files\R\R-4.1.3\library\cli\libs\x64\cli.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.1.3\library\00LOCK\rlang\libs\x64\rlang.dll to C:\Program Files\R\R-4.1.3\library\rlang\libs\x64\rlang.dll: Permission denied
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.1.3\library\00LOCK\Rcpp\libs\x64\Rcpp.dll to C:\Program Files\R\R-4.1.3\library\Rcpp\libs\x64\Rcpp.dll: Permission denied
4: In i.p(...) :
  installation of package ‘C:/Users/lgawarec/AppData/Local/Temp/Rtmp8gy3Lz/file2bc81346248c/torchvision_0.5.1.9000.tar.gz’ had non-zero exit status
> # torch_tensor(1, device = "cuda") Not woking on my computer
> devtools::install_github("mlverse/torchvision")
Downloading GitHub repo mlverse/torchvision@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: cli   (3.6.0   -> 3.6.1 ) [CRAN]
5: rlang (1.0.6   -> 1.1.1 ) [CRAN]
6: Rcpp  (1.0.8.3 -> 1.0.10) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
cli   (3.6.0   -> 3.6.1 ) [CRAN]
rlang (1.0.6   -> 1.1.1 ) [CRAN]
Rcpp  (1.0.8.3 -> 1.0.10) [CRAN]
Installing 3 packages: cli, rlang, Rcpp

  There is a binary version available but the source version is
  later:
      binary source needs_compilation
rlang  1.1.0  1.1.1              TRUE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/cli_3.6.1.zip'
Content type 'application/zip' length 1388241 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/Rcpp_1.0.10.zip'
Content type 'application/zip' length 3291415 bytes (3.1 MB)
downloaded 3.1 MB

package ‘cli’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘cli’
Warning: restored ‘cli’
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
Warning: restored ‘Rcpp’

The downloaded binary packages are in
	C:\Users\lgawarec\AppData\Local\Temp\Rtmp8gy3Lz\downloaded_packages
installing the source package ‘rlang’

trying URL 'https://cran.rstudio.com/src/contrib/rlang_1.1.1.tar.gz'
Content type 'application/x-gzip' length 762533 bytes (744 KB)
downloaded 744 KB

* installing *source* package 'rlang' ...
** package 'rlang' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Program Files/R/R-4.1.3/library/rlang'
* restoring previous 'C:/Program Files/R/R-4.1.3/library/rlang'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Program Files\R\R-4.1.3\library\00LOCK-rlang\rlang\libs\x64\rlang.dll to C:\Program Files\R\R-4.1.3\library\rlang\libs\x64\rlang.dll: Permission denied

The downloaded source packages are in
	‘C:\Users\lgawarec\AppData\Local\Temp\Rtmp8gy3Lz\downloaded_packages’
-- R CMD build -------------------------------------------------------------
v  checking for file 'C:\Users\lgawarec\AppData\Local\Temp\Rtmp8gy3Lz\remotes2bc85107772b\mlverse-torchvision-2d8b936/DESCRIPTION' ...
-  preparing 'torchvision':
v  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'torchvision/vignettes/examples'
   Removed empty directory 'torchvision/vignettes'
-  building 'torchvision_0.5.1.9000.tar.gz'
   
* installing *source* package 'torchvision' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'torchvision'
    finding HTML links ... done
    base_loader                             html  
    cifar10_dataset                         html  
    draw_bounding_boxes                     html  
    draw_keypoints                          html  
    draw_segmentation_masks                 html  
    image_folder_dataset                    html  
    kmnist_dataset                          html  
    magick_loader                           html  
    mnist_dataset                           html  
    model_alexnet                           html  
    model_inception_v3                      html  
    model_mobilenet_v2                      html  
    model_resnet                            html  
    model_vgg                               html  
    tensor_image_browse                     html  
    tensor_image_display                    html  
    tiny_imagenet_dataset                   html  
    transform_adjust_brightness             html  
    transform_adjust_contrast               html  
    transform_adjust_gamma                  html  
    transform_adjust_hue                    html  
    transform_adjust_saturation             html  
    transform_affine                        html  
    transform_center_crop                   html  
    transform_color_jitter                  html  
    transform_convert_image_dtype           html  
    transform_crop                          html  
    transform_five_crop                     html  
    transform_grayscale                     html  
    transform_hflip                         html  
    transform_linear_transformation         html  
    transform_normalize                     html  
    transform_pad                           html  
    transform_perspective                   html  
    transform_random_affine                 html  
    transform_random_apply                  html  
    transform_random_choice                 html  
    transform_random_crop                   html  
    transform_random_erasing                html  
    transform_random_grayscale              html  
    transform_random_horizontal_flip        html  
    transform_random_order                  html  
    transform_random_perspective            html  
    transform_random_resized_crop           html  
    transform_random_rotation               html  
    transform_random_vertical_flip          html  
    transform_resize                        html  
    transform_resized_crop                  html  
    transform_rgb_to_grayscale              html  
    transform_rotate                        html  
    transform_ten_crop                      html  
    transform_to_tensor                     html  
    transform_vflip                         html  
    vision_make_grid                        html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'torchvision' in library.dynam(lib, package, package.lib):
 DLL 'torchpkg' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-4.1.3/library/torchvision'
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.1.3\library\00LOCK\cli\libs\x64\cli.dll to C:\Program Files\R\R-4.1.3\library\cli\libs\x64\cli.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.1.3\library\00LOCK\Rcpp\libs\x64\Rcpp.dll to C:\Program Files\R\R-4.1.3\library\Rcpp\libs\x64\Rcpp.dll: Permission denied
3: In i.p(...) : installation of package ‘rlang’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘C:/Users/lgawarec/AppData/Local/Temp/Rtmp8gy3Lz/file2bc81fdcf9c/torchvision_0.5.1.9000.tar.gz’ had non-zero exit status
> install.packages("torchvision")

  There is a binary version available but the source version is
  later:
            binary source needs_compilation
torchvision  0.5.0  0.5.1             FALSE

installing the source package ‘torchvision’

trying URL 'https://cran.rstudio.com/src/contrib/torchvision_0.5.1.tar.gz'
Content type 'application/x-gzip' length 2009611 bytes (1.9 MB)
downloaded 1.9 MB

* installing *source* package 'torchvision' ...
** package 'torchvision' successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'torchvision'
    finding HTML links ... done
    base_loader                             html  
    cifar10_dataset                         html  
    draw_bounding_boxes                     html  
    draw_keypoints                          html  
    draw_segmentation_masks                 html  
    image_folder_dataset                    html  
    kmnist_dataset                          html  
    magick_loader                           html  
    mnist_dataset                           html  
    model_alexnet                           html  
    model_inception_v3                      html  
    model_mobilenet_v2                      html  
    model_resnet                            html  
    model_vgg                               html  
    tensor_image_browse                     html  
    tensor_image_display                    html  
    tiny_imagenet_dataset                   html  
    transform_adjust_brightness             html  
    transform_adjust_contrast               html  
    transform_adjust_gamma                  html  
    transform_adjust_hue                    html  
    transform_adjust_saturation             html  
    transform_affine                        html  
    transform_center_crop                   html  
    transform_color_jitter                  html  
    transform_convert_image_dtype           html  
    transform_crop                          html  
    transform_five_crop                     html  
    transform_grayscale                     html  
    transform_hflip                         html  
    transform_linear_transformation         html  
    transform_normalize                     html  
    transform_pad                           html  
    transform_perspective                   html  
    transform_random_affine                 html  
    transform_random_apply                  html  
    transform_random_choice                 html  
    transform_random_crop                   html  
    transform_random_erasing                html  
    transform_random_grayscale              html  
    transform_random_horizontal_flip        html  
    transform_random_order                  html  
    transform_random_perspective            html  
    transform_random_resized_crop           html  
    transform_random_rotation               html  
    transform_random_vertical_flip          html  
    transform_resize                        html  
    transform_resized_crop                  html  
    transform_rgb_to_grayscale              html  
    transform_rotate                        html  
    transform_ten_crop                      html  
    transform_to_tensor                     html  
    transform_vflip                         html  
    vision_make_grid                        html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'torchvision' in library.dynam(lib, package, package.lib):
 DLL 'torchpkg' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-4.1.3/library/torchvision'
Warning in install.packages :
  installation of package ‘torchvision’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\lgawarec\AppData\Local\Temp\Rtmp8gy3Lz\downloaded_packages’

**Comment by gaborcsardi** [comment]
Why do you think that this error is related to the pkgbuild package?

**Comment by lgawarec** [comment]
Honestly, I didn't know where to post this question. I am sorry. I will try
to take it off.

**Comment by gaborcsardi** [comment]
This is the issue tracker of torchvision: https://github.com/mlverse/torchvision/issues

**Comment by lgawarec** [comment]
Thank you very much.
