### ISSUE TITLE
Suboptimal display of R CMD

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgbuild#17]
pkgbuild:

```
Running command /Library/Frameworks/R.framework/Resources/bin/R 
Arguments:
CMD
build
/Users/hadley/Documents/devtools/devtools
--no-resave-data
--no-manual
```

CRAN devtools:

```
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build  \
  '/Users/hadley/Documents/devtools/devtools' --no-resave-data --no-manual 
```

**Comment by gaborcsardi** [comment]
This is coming from `callr`. The reason it is printed this way, is that in `callr`/`processx`, one does not need to quote the command and the arguments, and if we printed it as a command line, it would be misleading, often you could not run it as printed. Quoting it might be also fragile.

**Comment by hadley** [comment]
One argument per line makes the argument too prominent in the output. It's not _that_ important.  I don't think it matters that we might be printing something that wouldn't work if you literally copy and pasted into the terminal.

**Comment by gaborcsardi** [comment]
> It's not that important.

Agree completely, I just wanted to explain why it is printed that way. Then maybe pkgbuild could just call `callr` with `show` = FALSE here:
https://github.com/r-lib/pkgbuild/blob/a70858fbd5d249af6f365f9f03e48382ec6856ac/R/build.r#L85
and here:
https://github.com/r-lib/pkgbuild/blob/459ba5b00272d3094a4cb7714ed2ee82f6cb7c0e/R/compile-dll.r#L154

And `pkgbuild` could just print the command itself, in `rcmd_build_tools`?

Or is it important to show which R version is invoked?

**Comment by jimhester** [comment]
I think the callr output has changed since this was opened, and now is on one line, similar to the old devtools output did.
