### ISSUE TITLE
(very minor) Missing closing parenthesis in compiler_flags() docs

### ISSUE THREAD

**Issue by remlapmot** [r-lib/pkgbuild#179]
I was reading the `compiler_flags()` helpfile and noticed these parentheses need closing, i.e., just needs a `)` at the end of the following line.

https://github.com/r-lib/pkgbuild/blob/0ba4c619c8fd649bb69152e891ba5be4dcb85f5f/R/compiler-flags.R#L12

**Comment by gaborcsardi** [comment]
Would you like to submit a pull request? (No pressure.)
