### ISSUE TITLE
Add support for R 4.4.0

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgbuild#183]
I.e. Rtools44.

**Comment by sjmgarnier** [comment]
Checking the cache gives: 

```r
> pkgbuild:::cache_exists("rtools_path")
[1] TRUE
> pkgbuild:::cache_get("rtools_path")
character(0)
```

**Comment by eduardszoecs** [comment]
This still fails because [`version_info`](https://github.com/r-lib/pkgbuild/blob/4fe21d2a77379d5a614b57c0d5529030aca4d780/R/rtools-metadata.R#L1) was not updated in https://github.com/r-lib/pkgbuild/commit/518d65e61735fd60a8b4b6eb471d9791fabad578
