### ISSUE TITLE
Color the output of the compiler

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgbuild#20]
Both `gcc` and `clang` support ANSI colored output now, so (if possible) we can force-enable this, if we are sure that the R console supports ANSI colors.

**Comment by gaborcsardi** [comment]
At the same time, we can turn off the `stderr` coloring that `processx::run()` is automatically doing. R sends some non-error messages to `stderr`, so you get red output, even without errors.

**Comment by jimhester** [comment]
Alternatively we could color the errors ourselves, which might be simpler than trying to force gcc / clang coloring of output. 

e.g. https://github.com/r-lib/pkginstall/commit/c806b6c62a338e42fd887dd5099b7f291506ee81#diff-e8db8a52da7237909005b4230e99a57eR82

**Comment by gaborcsardi** [comment]
Maybe it is just `-fcolor-diagnostics` for clang?

**Comment by gaborcsardi** [comment]
And for gcc as well, seemingly.

**Comment by jimhester** [comment]
The issue isn't really the specific arguments, it is making sure we set them without clobbering existing options, that they produce color output in non tty sessions and that they are available in all compiler versions

**Comment by gaborcsardi** [comment]
The clang colors are quite sophisticated, I am not sure if I want to color the output myself. Especially as clang knows what it is outputting, and we can only guess, at least in some cases.

**Comment by jimhester** [comment]
WIP at https://github.com/r-lib/pkgbuild/pull/28

**Comment by gaborcsardi** [comment]
💯
