### ISSUE TITLE
Provide a hook to set compile flags

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgbuild#21]
Ideally, I would like to set them dynamically, to set the debug level of the C code.

The user sets the `DEBUGME` environment variable to turn on debugging for some packages, and set their debug level. This could automatically work for C code as well (after recompiling), if I had a way to change the compiler flags.

**Comment by jimhester** [comment]
You should be able to do with using `with_debug()`

https://github.com/r-lib/pkgbuild/blob/459ba5b00272d3094a4cb7714ed2ee82f6cb7c0e/R/with-debug.R#L20-L32

**Comment by jimhester** [comment]
@gaborcsardi is this sufficient, can I close this issue, or do you need something more?

**Comment by gaborcsardi** [comment]
Well, I can't really use this unfortunately, because I am not actively running anything. But anyway, not just a big issue.
