### ISSUE TITLE
Better documentation for rtools on windows

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgbuild#24]
* How does it find it?
* How do you tell if everything is ok?
* Should you set system path? (no)
* When do you need to manually use `with_build_tools()`?

**Comment by jimhester** [comment]
I guess these should be in `?has_roots`?.

I actually don't know the answer to the last question...

**Comment by jimhester** [comment]
Actually I kind of feel like this is already described in `?has_rtools`

> To build binary packages on windows, Rtools (found at
\url{https://CRAN.R-project.org/bin/windows/Rtools/}) needs to be on
the path. The default installation process does not add it, so this
script finds it (looking first on the path, then in the registry).
It also checks that the version of rtools matches the version of R.
`has_rtools()` determines if Rtools is installed, caching the results.
Afterward, run `rtools_path()` to find out where it's installed.

Going to close this for now, we can re-open if we think more documentation is still needed (or references to the has_rtools documentation).

**Comment by jimhester** [comment]
So had to do some work in the windows VM for other pkgbuild things, and was able to answer your questions myself and add some additional documentation relating to them in 50b786a
