### ISSUE TITLE
--resave-data argument to the build function gets overwritten internally

### ISSUE THREAD

**Issue by theGreatWhiteShark** [r-lib/pkgbuild#26]
Unless the `binary` argument was set to `TRUE`, the `build()` function automatically appends the `--no-resave-data` flag to the `args` argument.

If the user now want her data to be compressed by using the following command

> build( ".", args = "--resave-data" )

both the `--no-resave-data` and `--resave-data` option are provided as arguments to the call of `R CMD build`. 

This causes the argument provided by the user to be overwritten and renders the `build` function unable to compress the data.

**Comment by jimhester** [comment]
Closed by #27
