### ISSUE TITLE
pkg_build_bg: build in the background

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgbuild#30]
and return a callr / processx process. Maybe not too hard with `callr::rcmd_process` and/or `callr::rcmd_bg`.

**Comment by gaborcsardi** [comment]
Or, maybe just `pkg_build_process`, similarly to `rcmdcheck_process`.

**Comment by jimhester** [comment]
Closed by https://github.com/r-lib/pkgbuild/pull/32
