### ISSUE TITLE
Provide option to avoid recompilation of Rcpp attributes

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgbuild#33]
for pkginstall.

**Comment by jimhester** [comment]
I think actually we want to do one of two things

1. Always compile the attributes twice
2. Delete existing files before re-compiling attributes

See https://github.com/RcppCore/Rcpp/issues/745 for reasons why this happens and the remedies.

**Comment by gaborcsardi** [comment]
I think it also makes sense not to touch packages that were already R CMD built. I think the behavior could be different for a source directory and a proper tar.gz package, at least for pkginstall.

**Comment by jimhester** [comment]
I don't think it is guaranteed that attributes compiled with older versions of Rcpp would necessarily work with newer versions of Rcpp.

**Comment by jimhester** [comment]
Using https://github.com/r-lib/pkgbuild/commit/ef8dccc41d722cc7bb71cd35c29c1d69f407e07a the attributes are stable (and work) for the CRAN version of bindrcpp

**Comment by gaborcsardi** [comment]
> I don't think it is guaranteed that attributes compiled with older versions of Rcpp would necessarily work with newer versions of Rcpp.

Wow, so some older source packages cannot be installed with the current Rcpp?

**Comment by jimhester** [comment]
I don't think this has ever happened in practice
