### ISSUE TITLE
Should we call R CMD build before R CMD INSTALL when building binary packages

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgbuild#37]
According to WRE, that seems to be the proper way.  So far I only noticed small differences when calling `R CMD INSTALL --build` on the folder directly:
- The `NeedsCompilation` field is not added to `DESCRIPTION`
- The `Packaged` field is not added to `DESCRIPTION`

But there might be other differences, since `R CMD build` does other things as well:
- it runs the `cleanup` script, if there is one 
- converts line endings of source files
- adds a datalist file, although only for non-lazy data, so not really relevant any more I guess
- maybe more???

Should we run R CMD INSTALL --build on the result of R CMD build?

Also related: #34

**Comment by jimhester** [comment]
Don't you need to call `R CMD build` first to get `Authors@R` to populate?

**Comment by gaborcsardi** [comment]
If yes, then that's another reason to call `R CMD build` first.

**Comment by gaborcsardi** [comment]
No, it seems like `R CMD INSTALL` does that as well.

**Comment by jimhester** [comment]
So I am trying to get pkgbuild ready for CRAN submission in the next day or so, do we need this in the upcoming release or can it wait until the next one?

**Comment by gaborcsardi** [comment]
It can wait. pkgman always calls R CMD build first, anyway.

**Comment by gaborcsardi** [comment]
Seems like we are fine without this, so I am closing it.
