### ISSUE TITLE
Rtools 3.5 can work with R 3.3.* and up

### ISSUE THREAD

**Issue by coatless** [r-lib/pkgbuild#38]
The check that `pkgbuild` issues during the `devtools::check()` routine is too restrictive because Rtools 3.5 works with R 3.4. For details, please see the Rtools page:

https://cran.r-project.org/bin/windows/Rtools/

The affected code can be found here: 

https://github.com/r-lib/pkgbuild/blob/fb4534000cf04bb046c8e05fa45c5983da80e075/R/rtools.R#L49-L64

**Comment by jeroen** [comment]
+1, rtools 3.3, 3.4, 3.5 are basically interchangeable.

**Comment by jeroen** [comment]
OK cool. I'm about to open source the rtools installer itself so perhaps we can find a way to make this all a bit less convoluted.

**Comment by jimhester** [comment]
Sounds good to me!

**Comment by coatless** [comment]
@jeroen please ping me when you do that. More than happy to help with compile toolchain.

**Comment by jimhester** [comment]
That depends on CRAN, I submitted pkgbuild on March 19th, and it has been in CRAN limbo since then.

**Comment by jeroen** [comment]
Th escripts for building the rtools installer bundle are at https://github.com/rwinlib/rtools35

**Comment by coatless** [comment]
@jimhester :'(
@jeroen Thanks!

**Comment by Auds100** [comment]
Hi, I am a newbie, any step-by-step guide to how to solve the problem with Rtools not being recognized by v3.5?

**Comment by jeroen** [comment]
You can either modify your Windows system PATH, or instead define a line 
like below in your ".Renviron" file in your Documents folder. See also
the manual page for ?Startup in R for saving variables.

    PATH="C:\Rtools\bin;${PATH}"

Note that Windows PATH uses backslashes.
