### ISSUE TITLE
Failure with new rtools

### ISSUE THREAD

**Issue by jeroen** [r-lib/pkgbuild#40]
See https://github.com/r-windows/checks/blob/master/pkgbuild.Rcheck/00check.log

**Comment by jeroen** [comment]
This is the best logic to find rtools I think:

```r
test_rtools <- function(){
  make <- Sys.which('make')
  if(!nchar(make))
    stop("Did not find 'make' on the PATH")
  R <- file.path(R.home('bin'), 'R')
  CXX <- system2(R, c("CMD", "config", "CXX"), stdout = TRUE)
  if(!nchar(CXX))
    stop("Failed to lookup 'R CMD config CXX'")
  src <- tempfile(fileext = '.cpp')
  obj <- sub('cpp$', 'o', src)
  writeLines(testprog, con = src)
  out <- system2('make', c(obj, paste0("CXX=", CXX)), stdout = TRUE, stderr = TRUE)
  if(!file.exists(obj))
    stop("Failed to compile example program: ", out)
  TRUE
}

testprog <- '
#include <iostream>
int main() {
  std::cout << "Hello World!";
}'

```

**Comment by jimhester** [comment]
So https://github.com/r-lib/pkgbuild/pull/44 will provide at least partial support for the toolchain using the release version of R.

I needed to add the Rtools.txt and appropriate VERSION.txt files so that the pkgbuild detection would work.

Previous rtools builds added registry entries to the 32 bit registry rather than the 64 bit registry. It would be nice to do the same for rtools 4.0.

It would also be useful to retain the `mingw_64` `mingw_32` folders with the underscores as done in previous rtools versions, but maybe this is not really feasible to work with msys2?

**Comment by jeroen** [comment]
This is still not working and it is one of the packages blocking the toolchain migration.

> Previous rtools builds added registry entries to the 32 bit registry rather than the 64 bit registry. It would be nice to do the same for rtools 4.0.

The new rtools has a 64bit runtime (make, bash etc), so that is why it uses the 64-bit registry. How is this a problem? I could try to hack something but I'm not sure you should need the registry at all.


> It would also be useful to retain the mingw_64 mingw_32 folders with the underscores as done in previous rtools versions, but maybe this is not really feasible to work with msys2?

Indeed, we use `/mingw32` and `/mingw64` from the msys2 layout.

I'm not sure why this is relevant though. All that you need to find the compiler for a given version of R is check `R CMD config CC`. Can we make that `pkgbuild` just respects this?



```
> library(pkgbuild)
> pkgbuild::check_build_tools(debug = TRUE)
Scanning R CMD config CC...
cc_path: c:/rtools40/mingw64/bin/gcc
install_path: c:/rtools40
Scanning path...
ls: C:\rtools40\usr\bin\ls.exe
gcc_path: C:\rtools40\mingw64\bin\gcc.exe
Scanning registry...
WARNING: Rtools is required to build R packages, but is not currently installed.


Please download and install Rtools 3.5 from http://cran.r-project.org/bin/window
s/Rtools/.

```
