### ISSUE TITLE
Cannot Build with Rtools installed in Documents folder

### ISSUE THREAD

**Issue by melondonkey** [r-lib/pkgbuild#65]
I can't install Rtools on C: because of restrictions in my corporate environment.  I am having trouble running rstan due to the build tools not being recognized.  I tried the Stan forums first, but they redirected me to open an issue with pkgbuild as it seems to be the source.  

https://discourse.mc-stan.org/t/rstan-always-trying-to-download-rtools-when-its-already-installed/7682/12

``` r
pkgbuild::with_build_tools("print(“hello”)", debug = TRUE)
#> Scanning R CMD config CC...
#> cc_path:  
#> '.exe' does not exist
#> Scanning path...
#> Scanning registry...
#> Found C:/Users/josephdean/Documents/Rtools for 3.5 
#> VERSION.txt
#> Rtools version 3.5.0.4
#> [1] "print(“hello”)"
```

<sup>Created on 2019-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bgoodri** [comment]
Specifically, as I understand it, when Rtools is installed to a writable location, `with_build_tools` does not find it and wants to re-download Rtools each time when called from RStudio.

**Comment by cderv** [comment]
This was suggested in the discourse topic you linked, but I opened an issue in RStudio some time ago
https://github.com/rstudio/rstudio/issues/3563

It has been closed - you need to try the preview or even last daily to see if it works for you. If not, it seems it needs some more work.

**Comment by jimhester** [comment]
pkgbuild seems to be finding it fine, does what you are trying to do work outside of RStudio? If so then it is a bug in the RStudio IDE, not pkgbuild.

**Comment by cderv** [comment]
pkgbuild works fine on its own but offer a mechanism to bypass its own way of finding rtools with an option `buildtools.check`. https://github.com/r-lib/pkgbuild/blob/9996f08e1c733173487f63485024b3445ca44f90/R/build-tools.R#L26-L29

indeed RStudio IDE [uses that option](https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/cpp/session/modules/SessionBuild.R#L60) for bypassing the pkgbuild mechanism using [`.rs.checkBuildTools`](https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/SessionBuild.R#L38-L52)
```r
function(action) {

   if (identical(.Platform$pkgType, "mac.binary.mavericks")) {
      # this will auto-prompt to install on mavericks
      .Call("rs_canBuildCpp")
   } else {
      if (!.Call("rs_canBuildCpp")) {
        .rs.installBuildTools(action)
        FALSE
      }
      else {
        TRUE;
      }
}
```
So yes there is some interaction with RStudio IDE. Don't know if it is a bug but pkgdown way of finding Rtools is used (and working) only if outside the ide. It was mentioned in https://github.com/rstudio/rstudio/issues/3563, dicussing how `.Call("rs_canBuildCpp")` was working.

**Comment by dflynn-volpe** [comment]
I'm in a similar situation. With Rtools installed at C:/RBuildTools, I get the following:
``` r
pkgbuild::has_rtools(debug = T)
#> Scanning R CMD config CC...
#> cc_path:  
#> '.exe' does not exist
#> Scanning path...
#> Scanning registry...
#> Found C:/RBuildTools/3.5 for 3.5 
#> VERSION.txt
#> Rtools version 3.5.0.4
#> [1] TRUE
```

<sup>Created on 2019-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This appears to be the source of several other issues, including `pkgbuild::has_build_tools(debug = TRUE)` insisting on downloading and installing Rtools, but without any resolution. Any tips?

**Comment by cderv** [comment]
@dflynn-volpe `pkgbuild::has_rtools()` is `TRUE` here and found Rtools in `C:/RBuildTools/3.5`. 
This is correct here. 

About the situation describe in the first two posts here, it concerns `pkgbuild` behavioir in RStudio. RStudio has its own detection algorithm that is activated by `pkgbuild` when run inside RStudio. The RStudio mechanism offer to download rtools if not found. Please try last preview version where the RStudio detection has been improved on windows. refer to rstudio/rstudio#3563. This is not a bug in `pkgbuild`. 


Otherwise, The workaround is to deactivate RStudio detection algorithm by running this in the session before calling `pkgbuild`
```r
options(buildtools.check = NULL)
```

**Comment by dflynn-volpe** [comment]
Hi @cderv, Thanks for clarifying. The [RStudio Preview](https://www.rstudio.com/products/rstudio/download/preview/) did not solve the problem, but your deactivation trick works. For me, having this in my .Rprofile closes the issue:
```{r}
options(buildtools.check = NULL)
```
