### ISSUE TITLE
Have vignettes not be deleted if "BuildVignettes: no" in DESCRIPTION

### ISSUE THREAD

**Issue by schloerke** [r-lib/pkgbuild#75]
While the 95% case is to build vignettes every time from source, I'd like to be able to not have to manually set `vignettes = FALSE` in `pkgbuild::build` if in the DESCRIPTION file states `BuildVignettes: no`.

This would be very handy.

**Comment by schloerke** [comment]
@alandipert for shinyloadtest

**Comment by jimhester** [comment]
Ok, did try it? pkgbuild is just delegating to `R CMD build`, so this should already work and does seem to in a simple test package.

**Comment by schloerke** [comment]
Yes.  I'm trying on repo [`rstudio/sortable@pkgdown`](https://github.com/rstudio/sortable/blob/19dd6743ef59724b77c07f35014518ecb9ddfb9c/DESCRIPTION#L35)

If I call `devtools::check()`, it still asks if it can delete `./inst/doc`, which I don't want it to do.
If I respond, "No", the build stops.

Calling `devtools::check(vignettes = FALSE)` gives me the desired behavior of not asking about deleting `./inst/doc` and not building the vignettes.

**Comment by jimhester** [comment]
deleting `inst/doc` is different than building the vignettes...

**Comment by gaborcsardi** [comment]
I think it would be great to document the newly suggested vignette workflow, and also how people show go about _not_ rebuilding the vignettes all the time.

**Comment by jimhester** [comment]
You can now use `clean_doc = FALSE` to avoid cleaning the `inst/doc` folder.
