### ISSUE TITLE
RdWarnings when installing pkgbuild

### ISSUE THREAD

**Issue by boxcoxuser** [r-lib/pkgbuild#84]
While installing pkgbuild, I get warning of the form
Rd warning: Rd warning: C:/Users/user/AppData/Local/Temp/Rtmpklq0bG/R.INSTALL52414f64478/pkgbuild/man/rcmd_build_tools.Rd:14: file link 'rcmd_safe_env' in package 'callr' does not exist and so has been treated as a topic

**Comment by cderv** [comment]
Thanks for the report. 

These warnings are not bad per-se. This is a known issue on windows with how base R works. 
See discussion in https://github.com/r-lib/roxygen2/issues/707

Also, the links is still working in the documentation so it is just R which warns but it has no impact.
> Because they have been frequently misused, the HTML help system looks for topic foo in package pkg if it does not find file foo.html. 

From Writing R extension.
