### ISSUE TITLE
pkgbuild fails on macOS 10.15.1

### ISSUE THREAD

**Issue by kylelundstedt** [r-lib/pkgbuild#88]
Trying to install `r-dbi/odbc`.

```
Downloading GitHub repo r-dbi/odbc@master
Error: Failed to install 'odbc' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```

When I run check_build_tools, it's not helpful.
```
> pkgbuild::check_build_tools(debug = TRUE)
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```

The web page that opens doesn't help either.  Command line tools are already installed.

**Comment by jimhester** [comment]
What operating system are you using?

**Comment by kylelundstedt** [comment]
Yes, I did accept the CLI tools agreement.  I confirmed by running `xcode-select --install` and receiving the "command line tools are already installed".  Also ran `make` and `gcc` separately without an issue.

**Comment by kylelundstedt** [comment]
macOS 10.15 Catalina

**Comment by jimhester** [comment]
I and others also use Catalina and have no problems. If you can figure out what makes your local environment different so we can reproduce the issue I can reopen this.
