### ISSUE TITLE
Rtools 3.4 compatibility with R 3.6.2

### ISSUE THREAD

**Issue by brianstamper** [r-lib/pkgbuild#90]
Per request relocating an issue I had started here: https://github.com/rwinlib/base/issues/23

Running R 3.6.2 on RStudio 1.2.5033 on Windows, when I do install.packages() I get a warning saying that my current Rtools 3.4 is not compatible with my current R:

> \> install.packages('glmnet')
> WARNING: Rtools is required to build R packages but no version of Rtools compatible with the currently running version of R was found. Note that the following incompatible version(s) of Rtools were found:
> 
>   - Rtools 3.4 (installed at C:\RBuildTools\3.4)
>   - Rtools 3.4 (installed at C:\RBuildTools\3.4)
> 
> Please download and install the appropriate version of Rtools before proceeding

After which it proceeds to successfully install the package, but I suspect that just happens to not be relevant in this case. I could upgrade to Rtools 3.5 but for my employer-managed computer I need to request that from IT and I'm trying to keep the maintenance requests low (especially if it isn't actually necessary).

**Comment by jimhester** [comment]
Should now be fixed.
